### ISSUE TITLE
Icon always shows motion detected 

### ISSUE THREAD

**Issue by averagebald** [veonua/SmartThingsEdge-Xiaomi#10]
Hi,

First of all thanks for these drivers they are working well for me so far. One thing that i just noticed was the icon for aqara motion sensor stays "motion detected" even when there is no motion. And somehow, illuminance is not working for me. When you have a chance, please help check. Thanks man!!! 

![Screenshot_20220521-050045_SmartThings](https://user-images.githubusercontent.com/91673397/169610523-9a85747c-3ca7-4b13-b65e-75223e0ef2d2.jpg)

**Comment by veonua** [comment]
Hello, I'll check the icon, 
but the icon view is on the ST side and I just copied the snippet from the zigbee motion driver.
Are you sure that there are two icons for this type of device? 

as for illuminance, can you please provide a log from cli. it's hard to debug without log

**Comment by veonua** [comment]
please check now
