### ISSUE TITLE
Compared to Orangebucket DTH

### ISSUE THREAD

**Issue by petrivgs** [veonua/SmartThingsEdge-Xiaomi#13]
yes i know this is not the discussion forum but do other edge drivers have with temp sensor 0 values ?

I've been running old orangebucket DTH and i havent't seen no zero values

Problem with edge is temperature is zero once in a while and i dont know why

From logs you can see zero values.. code has return... <- thus is it zero return when value is not wanted  ?

**Comment by veonua** [comment]
can you share your log
