### ISSUE TITLE
Aqara Cube

### ISSUE THREAD

**Issue by LionMike** [veonua/SmartThingsEdge-Xiaomi#5]
Stopped working after the latest driver update. I tried uninstalling the driver but cannot because it is "in use". What next?

**Comment by veonua** [comment]
try to reboot the hub first.
if it would not work attach the log here

**Comment by LionMike** [comment]
What log do I attach?

**Comment by veonua** [comment]
from the cube, it's better to keep only warning and error messages

**Comment by LionMike** [comment]
After rebooting the hub, I can control dimmer through app but nothing else. I am getting a "network or sever error" message as well.
Where do I retrieve the log from?

**Comment by veonua** [comment]
https://lmgtfy.app/?q=smartthings+edge+log

**Comment by veonua** [comment]
@LionMike I've published a new version of the driver, now with the custom capability. 
it should look and work better

**Comment by LionMike** [comment]
Thank you. It is working fine now.
