### ISSUE TITLE
unable to pair Button

### ISSUE THREAD

**Issue by LionMike** [veonua/SmartThingsEdge-Xiaomi#7]
I have the WXKG01LM button that won't find the driver. It's connecting to the hub but that's it. Is there a certain procedure for pairing this with the driver?

**Comment by veonua** [comment]
connecting to the hub is all you need.
or I miss something.

if you have old DTH installed please uninstall it.

**Comment by LionMike** [comment]
That did not work either.

**Comment by veonua** [comment]
please contact Smartthings forums to get more information on how to install
drivers.

**Comment by LionMike** [comment]
ok. However I just successfully paired an Aqara motion sensor with your driver, without having to uninstall the DTH, and your Aqara cube driver is working just fine. I will keep trying. I have another button I can try to pair.
