### ISSUE TITLE
Unknown device is recognized as xiaomi-switch/opple-switch-2

### ISSUE THREAD

**Issue by kisuo** [veonua/SmartThingsEdge-Xiaomi#9]
It seems that any unknown device is always matched to `opple-switch-2`, and resulting that it is impossible to use DTH instead.

I scanned a zigbee device which doesn't need external driver. It should use pre-embedded `easyiot Light` DTH driver in ST hub.
-  deviceManufacturerCode: eWeLight
-  deviceModel: ZB-CL01
- raw descriptor info.
> Data application: 01
> endpointId: 01
> manufacturer: eWeLight
> model: ZB-CL01
> zigbeeNodeType: ROUTER
> Raw Description	01 0104 010D 01 08 0000 0003 0004 0005 0006 0008 0300 1000 00

But when I searched it, it is scanned as name `any` in ST app, and device type is recognized as edge driver of `opple-switch-2`.
I noticed that patterns like `^lumi.switch.l.aeu1` are used by `device:get_model():find(fingerprint.model)` only in `opple` subdriver code, but couldn't understand why it's happening.
To solve this issue, I had to remove every `opple` related code & lines from `fingerprint.yml` and subdriver setup, then I was able to use ST embedded DTH.

I also found another user is also reporting that his Si-Has sensors are also recognized as `any` `opple-switch-2`, and those sensors should use DTH driver instead.

Would you please review this issue?

Thank you.

**Comment by veonua** [comment]
"any" is removed now from the fingerprints
